### ISSUE TITLE
Question: How does UPS-Monitor Notifies work?

### ISSUE THREAD

**Issue by 5G7K** [Apollon77/ioBroker.nut#103]
I tried to use UPS-Monitor Notifies as described. But it does not work / I don't know what should happen. Can I see the message anywhere in ioBroker?

I tried it manually - can it be tested that way?
pi@raspberrypi:~ $ /opt/iobroker/iobroker message nut notify "{\"upsname\":\"$UPSNAME\",\"notifytype\":\"$NOTIFYTYPE\"}"
The command "notify" was sent to "system.adapter..nut" with the message "[object Object]".
pi@raspberrypi:~ $ /opt/iobroker/iobroker message nut notify "Test"
The command "notify" was sent to "system.adapter..nut" with the message "Test".

But I can't see anything in ioB / log.

In my system the following file can be found here: /opt/iobroker/node_modules/iobroker.nut/scripts/nut-notify.sh
From docu: NOTIFYCMD "cd /opt/iobroker/;./nut-notify.sh"
Is this statement correct for my configuration? Or should it be: NOTIFYCMD "cd /opt/iobroker/;/opt/iobroker/node_modules/iobroker.nut/scripts/nut-notify.sh" ?

Thank you for your help

**Comment by Apollon77** [comment]
When you send the message you ideally should set the instance id ... so "nut.0" and not just "nut". When the message was received yiu should see an "info" logline from the instance in any case and the state status.last_notify gets updated with the status value.

manually testing should also only work when you set real values insted of the Environment variables $UPSNAME and $NOTIFYTYPE" because they will be empty when you send it like in your test above.
